### ISSUE TITLE
Aggie Experts deployment

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-deployment#2]
The dev.experts.ucdavis.edu server is currently running two rp clusters, dev and sandbox.   It is already kinda slow.  Is this slowness from the RP apps?  Can the current server handle a third cluster (prod)?  How do we want to setup the rp clusters in terms of hardware.

**Comment by qjhart** [comment]
Have Requested two Production VMs and a routing server.  

Thanks for getting this underday. I guess my inclination is to give these all library DNS names;
router.experts.library.ucdavis.edu
blue.experts.library.ucdavis.edu
gold.experts.library.ucdavis.edu

and then (later) add a A record for *.experts.ucdavis.edu to router.experts.library.ucdavis.edu

**Comment by qjhart** [comment]
Need to verify that the dev only implementation is
-[ ] Development image pull works
-[ ] Fix DNS so that we point here for non-dev
-[ ] Determine the fate of sandbox.

**Comment by qjhart** [comment]
@jrmerz I suggest we do the following DNS changes
-  CNAME entry experts.ucdavis.edu -> router.experts.library.ucdavis.edu
-  CNAME entry *.experts.ucdavis.edu -> router.experts.library.ucdavis.edu
-  CNAME entry *.experts.library.ucdavis.edu -> router.experts.library.ucdavis.edu
- A sandbox.experts.ucdavis.edu -> 35.202.58.173  
  - This could also point to a UCD machine.
